"use client";
import { useState } from "react";
import { AlertCircle, ChevronLeft, ChevronRight, Download, LoaderCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { formatDuration } from "@/features/event-staffing/calculations";
import { formatDate, formatMoney } from "@/lib/hebrew";
import { useMonthlyPayroll } from "../hooks/use-payroll";
import { usePayrollPaymentStatus } from "../hooks/use-payroll-payment-status";
import type { EmployeePayroll } from "../types";
import { PayrollDetailsDialog } from "./payroll-details-dialog";

export function PayrollPage() {
  const [month, setMonth] = useState(currentMonth());
  const [details, setDetails] = useState<EmployeePayroll | null>(null);
  const query = useMonthlyPayroll(month);
  const { paidIds: paid, setPaid } = usePayrollPaymentStatus(month);
  const payroll = query.data;

  return <div className="mx-auto max-w-7xl space-y-6"><header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-medium text-muted-foreground">כספים</p><h2 className="mt-1 text-2xl font-semibold">משכורות</h2><p className="mt-2 text-sm text-muted-foreground">חישוב שכר חודשי לפי השיבוצים באירועים.</p></div><div className="flex flex-wrap items-center gap-2"><Button type="button" variant="outline" size="icon" onClick={() => setMonth(moveMonth(month, -1))} aria-label="החודש הקודם"><ChevronRight /></Button><label className="text-sm font-medium">חודש<input type="month" value={month} onChange={(event) => setMonth(event.target.value)} className="mr-2 h-9 rounded-lg border border-input bg-background px-3 text-sm" /></label><Button type="button" variant="outline" size="icon" onClick={() => setMonth(moveMonth(month, 1))} aria-label="החודש הבא"><ChevronLeft /></Button><Button type="button" variant="outline" disabled title="ייצוא יתווסף בהמשך"><Download />ייצוא דוח</Button></div></header>
    <p className="text-lg font-medium">{monthTitle(month)}</p>
    {query.isLoading ? <Loading /> : query.isError || !payroll ? <ErrorState /> : <><div className="grid grid-cols-2 gap-3 lg:grid-cols-5"><Summary label="סה״כ משכורות" value={formatMoney(payroll.totalAmount)} /><Summary label="עובדים" value={String(payroll.calculatedEmployeeCount)} /><Summary label="חסרות שעות" value={String(payroll.missingHoursCount)} warning={payroll.missingHoursCount > 0} /><Summary label="שולם" value={String(payroll.employees.filter((employee) => paid.has(employee.employeeId)).length)} /><Summary label="תאריך תשלום אחרון" value={formatDate(paymentDeadline(month))} /></div><PayrollList employees={payroll.employees} paid={paid} onDetails={setDetails} onPaid={setPaid} /></>}
    {details && <PayrollDetailsDialog payroll={details} onClose={() => setDetails(null)} />}
  </div>;
}

function PayrollList({ employees, paid, onDetails, onPaid }: { employees: EmployeePayroll[]; paid: Set<string>; onDetails: (employee: EmployeePayroll) => void; onPaid: (id: string, paid: boolean) => void }) { if (!employees.length) return <div className="grid min-h-64 place-items-center rounded-xl border border-dashed border-border bg-card p-8 text-center"><div><p className="font-medium">אין נתוני משכורות בחודש זה</p><p className="mt-1 text-sm text-muted-foreground">לא נמצאו שיבוצים באירועים בחודש שנבחר.</p></div></div>; return <section className="overflow-hidden rounded-xl border border-border bg-card shadow-sm"><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[1000px] text-right text-sm"><thead className="bg-muted/50 text-xs text-muted-foreground"><tr>{["שם מלא", "אירועים", "שעות עבודה", "שכר שעתי", "שכר גלובלי", "סה״כ לתשלום", "סטטוס תשלום", "פעולות"].map((label) => <th key={label} className="px-4 py-3.5 font-medium">{label}</th>)}</tr></thead><tbody className="divide-y divide-border">{employees.map((employee) => <tr key={employee.employeeId} className="hover:bg-muted/30"><td className="px-4 py-4 font-medium">{employee.fullName}</td><td className="px-4 py-4">{employee.eventCount}</td><td className="px-4 py-4">{formatDuration(employee.workedMinutes)}</td><td className="px-4 py-4">{formatMoney(employee.hourlyTotal)}</td><td className="px-4 py-4">{formatMoney(employee.fixedTotal)}</td><td className="px-4 py-4 font-medium">{formatMoney(employee.totalSalary)}</td><td className="px-4 py-4"><Status paid={paid.has(employee.employeeId)} /></td><td className="px-4 py-4"><Actions employee={employee} paid={paid.has(employee.employeeId)} onDetails={onDetails} onPaid={onPaid} /></td></tr>)}</tbody></table></div><div className="divide-y divide-border md:hidden">{employees.map((employee) => <article key={employee.employeeId} className="space-y-4 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-medium">{employee.fullName}</p><p className="mt-1 text-sm text-muted-foreground">{employee.eventCount} אירועים · {formatDuration(employee.workedMinutes)}</p></div><Status paid={paid.has(employee.employeeId)} /></div><div className="grid grid-cols-2 gap-3 text-sm"><Value label="שכר שעתי" value={formatMoney(employee.hourlyTotal)} /><Value label="שכר גלובלי" value={formatMoney(employee.fixedTotal)} /><Value label="סה״כ לתשלום" value={formatMoney(employee.totalSalary)} />{employee.missingHoursCount > 0 && <Value label="חסרות שעות" value={String(employee.missingHoursCount)} />}</div><Actions employee={employee} paid={paid.has(employee.employeeId)} onDetails={onDetails} onPaid={onPaid} /></article>)}</div></section>; }
function Actions({ employee, paid, onDetails, onPaid }: { employee: EmployeePayroll; paid: boolean; onDetails: (employee: EmployeePayroll) => void; onPaid: (id: string, paid: boolean) => void }) { return <div className="flex flex-wrap justify-end gap-2"><Button type="button" size="sm" variant="outline" onClick={() => onDetails(employee)}>פירוט משכורת</Button><Button type="button" size="sm" variant={paid ? "outline" : "default"} onClick={() => onPaid(employee.employeeId, !paid)}>{paid ? "בטל סימון תשלום" : "סמן כשולם"}</Button></div>; }
function Status({ paid }: { paid: boolean }) { return <span className={`rounded-full px-2.5 py-1 text-xs font-medium ${paid ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{paid ? "שולם" : "טרם שולם"}</span>; }
function Summary({ label, value, warning = false }: { label: string; value: string; warning?: boolean }) { return <div className="rounded-xl border border-border bg-card p-4 shadow-sm"><p className="text-xs text-muted-foreground">{label}</p><p className={`mt-2 text-lg font-semibold ${warning ? "text-amber-700" : ""}`}>{value}</p></div>; }
function Value({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1">{value}</p></div>; }
function Loading() { return <div className="grid min-h-80 place-items-center rounded-xl border bg-card"><span className="flex items-center gap-2 text-sm text-muted-foreground"><LoaderCircle className="size-4 animate-spin" />טוען נתוני משכורות...</span></div>; }
function ErrorState() { return <div className="grid min-h-80 place-items-center rounded-xl border border-dashed border-destructive/40 bg-card p-8 text-center"><div><AlertCircle className="mx-auto size-6 text-destructive" /><p className="mt-3 font-medium">לא ניתן לטעון את נתוני המשכורות</p><p className="mt-1 text-sm text-muted-foreground">בדקו את החיבור וההרשאות ונסו שוב.</p></div></div>; }
function currentMonth() { const date = new Date(); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`; }
function moveMonth(month: string, delta: number) { const [year, number] = month.split("-").map(Number); const date = new Date(year, number - 1 + delta, 1); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`; }
function monthTitle(month: string) { const [year, number] = month.split("-").map(Number); return new Intl.DateTimeFormat("he-IL", { month: "long", year: "numeric" }).format(new Date(year, number - 1, 1)); }
function paymentDeadline(month: string) { const [year, number] = month.split("-").map(Number); return new Date(year, number, 10); }
