"use client";
import { X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { formatAssignmentTime, formatDuration } from "@/features/event-staffing/calculations";
import { formatDate, formatMoney, translateStoredValue } from "@/lib/hebrew";
import type { EmployeePayroll } from "../types";

export function PayrollDetailsDialog({ payroll, onClose }: { payroll: EmployeePayroll; onClose: () => void }) {
  return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/40 p-4 sm:p-8" role="dialog" aria-modal="true" aria-labelledby="payroll-details-title"><div className="mx-auto w-full max-w-4xl rounded-xl bg-card shadow-xl"><div className="sticky top-0 z-10 flex items-center justify-between border-b border-border bg-card px-5 py-4"><div><h2 id="payroll-details-title" className="font-semibold">פירוט משכורת</h2><p className="mt-1 text-sm text-muted-foreground">{payroll.fullName}</p></div><Button type="button" variant="ghost" size="icon" onClick={onClose} aria-label="סגירה"><X /></Button></div><div className="space-y-3 p-5">{payroll.assignments.map((assignment) => { const missing = assignment.payType === "hourly" && assignment.salary === null; return <article key={assignment.id} className="rounded-lg border border-border p-4"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><p className="font-medium">{formatDate(assignment.eventDate)} · {assignment.venueName}</p><p className="mt-1 text-sm text-muted-foreground">{translateStoredValue(assignment.eventType)}</p></div>{missing && <span className="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-medium text-amber-700">חסרות שעות</span>}</div><dl className="mt-4 grid grid-cols-2 gap-4 text-sm sm:grid-cols-4"><Item label="סוג שכר" value={assignment.payType === "hourly" ? "שעתי" : "גלובלי"} /><Item label="שעות עבודה" value={durationText(assignment.workedMinutes, assignment.workStart, assignment.workEnd)} /><Item label={assignment.payType === "hourly" ? "שכר שעתי" : "שכר גלובלי"} value={formatMoney(assignment.payType === "hourly" ? assignment.hourlyRate ?? 0 : assignment.fixedPay ?? 0)} /><Item label="שכר מחושב" value={assignment.salary === null ? "טרם ניתן לחשב" : formatMoney(assignment.salary)} /></dl>{assignment.workStart || assignment.workEnd ? <p className="mt-3 text-xs text-muted-foreground">כניסה: {formatAssignmentTime(assignment.workStart)} · יציאה: {formatAssignmentTime(assignment.workEnd)}</p> : null}</article>; })}</div></div></div>;
}
function durationText(minutes: number | null, start: string | null, end: string | null) { if (Boolean(start) !== Boolean(end)) return "חסרה שעת כניסה או יציאה"; return minutes === null ? "טרם הוזנו שעות" : formatDuration(minutes); }
function Item({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs text-muted-foreground">{label}</dt><dd className="mt-1">{value}</dd></div>; }
