import { assertOwner } from "@/lib/auth/user";
import { createClient } from "@/lib/supabase/server";
import { expenseSchema } from "@/features/expenses/validation";

type ExpenseRow = { id:string; expense_date:string; category:string; supplier_name:string|null; description:string|null; amount:number|string; includes_vat:boolean; vat_rate:number|string; payment_method:string|null; reference_number:string|null; event_id:string|null; notes:string|null; created_at:string; updated_at:string };
const select = "id, expense_date, category, supplier_name, description, amount, includes_vat, vat_rate, payment_method, reference_number, event_id, notes, created_at, updated_at";
const map = (row:ExpenseRow) => ({ id:row.id, expenseDate:row.expense_date, category:row.category, supplierName:row.supplier_name??"", description:row.description??"", amount:Number(row.amount), includesVat:row.includes_vat, vatRate:Number(row.vat_rate), paymentMethod:row.payment_method??"", referenceNumber:row.reference_number??"", eventId:row.event_id??"", notes:row.notes??"", createdAt:row.created_at, updatedAt:row.updated_at });
const payload = (v:ReturnType<typeof expenseSchema.parse>) => ({ expense_date:v.expenseDate, category:v.category, supplier_name:v.supplierName.trim()||null, description:v.description.trim()||null, amount:v.amount, includes_vat:v.includesVat, vat_rate:v.vatRate, payment_method:v.paymentMethod||null, reference_number:v.referenceNumber.trim()||null, event_id:v.eventId||null, notes:v.notes.trim()||null });
async function owner(){ try { await assertOwner(); return null; } catch { return Response.json({error:"Unauthorized"},{status:403}); } }
export async function GET(){ const denied=await owner(); if(denied)return denied; const supabase=await createClient(); const [expenses,events]=await Promise.all([supabase.from("expenses").select(select).order("expense_date",{ascending:false}),supabase.from("events").select("id,event_date,client_name").order("event_date",{ascending:false})]); const error=expenses.error??events.error; if(error)return Response.json({error:error.message},{status:400}); return Response.json({expenses:((expenses.data??[]) as ExpenseRow[]).map(map),events:(events.data??[]).map(e=>({id:e.id,label:`${e.event_date} · ${e.client_name}`}))}); }
export async function POST(request:Request){ const denied=await owner(); if(denied)return denied; const body=await request.json() as unknown; const candidates=Array.isArray(body)?body:[body]; const parsed=candidates.map(value=>expenseSchema.safeParse(value)); if(parsed.some(result=>!result.success))return Response.json({error:"נתוני ההוצאה אינם תקינים"},{status:400}); const supabase=await createClient(); const {data,error}=await supabase.from("expenses").insert(parsed.map(result=>payload(result.data!))).select(select); if(error)return Response.json({error:error.message},{status:400}); return Response.json(((data??[]) as ExpenseRow[]).map(map),{status:201}); }
export async function PATCH(request:Request){ const denied=await owner(); if(denied)return denied; const body=await request.json() as {id?:string;values?:unknown}; const parsed=expenseSchema.safeParse(body.values); if(!body.id||!parsed.success)return Response.json({error:"נתוני ההוצאה אינם תקינים"},{status:400}); const supabase=await createClient(); const {data,error}=await supabase.from("expenses").update(payload(parsed.data)).eq("id",body.id).select(select).single(); if(error)return Response.json({error:error.message},{status:400}); return Response.json(map(data as ExpenseRow)); }
export async function DELETE(request:Request){ const denied=await owner(); if(denied)return denied; const id=new URL(request.url).searchParams.get("id"); if(!id)return Response.json({error:"מזהה חסר"},{status:400}); const supabase=await createClient(); const {error}=await supabase.from("expenses").delete().eq("id",id); if(error)return Response.json({error:error.message},{status:400}); return new Response(null,{status:204}); }
