"use client";

import { useState } from "react";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { LoaderCircle, Pencil, Plus, Trash2, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useMasterData } from "@/features/master-data";
import { formatDate, formatMoney, formatPaymentMethod, payerLabels, paymentStatusLabels } from "@/lib/hebrew";
import { calculatePaymentSummary } from "../calculations";
import { useCreateEventPayment, useDeleteEventPayment, useEventPayments, useUpdateEventPayment } from "../hooks/use-event-payments";
import type { EventPayment, EventPaymentValues } from "../types";
import { eventPaymentSchemaFor } from "../validation";

export function EventPaymentsSection({ eventId, totalDue, onSuccess, onError }: { eventId: string; totalDue: number; onSuccess: (message: string) => void; onError: (message: string) => void }) {
  const payments = useEventPayments(eventId);
  const methods = useMasterData("payment_methods");
  const [editing, setEditing] = useState<EventPayment | null | undefined>(undefined);
  const [deleting, setDeleting] = useState<EventPayment | null>(null);
  const summary = calculatePaymentSummary(totalDue, payments.data ?? []);
  return <section className="border-t border-border pt-7"><div className="flex items-center justify-between gap-3"><h3 className="text-sm font-semibold">תשלומים</h3><Button type="button" variant="outline" onClick={() => setEditing(null)} disabled={methods.isLoading}><Plus />הוספת תשלום</Button></div><div className="mt-4 grid grid-cols-2 gap-3 rounded-lg bg-muted/50 p-4 text-sm sm:grid-cols-4"><Summary label="סה״כ לתשלום כולל מע״מ" value={formatMoney(summary.totalDue)} /><Summary label="סה״כ שולם" value={formatMoney(summary.totalPaid)} /><Summary label="יתרה לתשלום" value={formatMoney(summary.remainingBalance)} /><Summary label="סטטוס תשלום" value={paymentStatusLabels[summary.status]} /></div>{summary.overpaid && <p className="mt-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-800">סכום התשלומים גבוה מסכום האירוע</p>}{payments.isLoading || methods.isLoading ? <State><LoaderCircle className="size-4 animate-spin" />טוען תשלומים...</State> : payments.isError || methods.isError ? <State>לא ניתן לטעון את התשלומים. נסו שוב.</State> : payments.data?.length ? <PaymentList payments={payments.data} onEdit={setEditing} onDelete={setDeleting} /> : <State>טרם הוזנו תשלומים לאירוע</State>}{editing !== undefined && <PaymentDialog eventId={eventId} payment={editing} paymentMethods={(methods.data ?? []).map((item) => item.name)} totalDue={totalDue} otherPaid={(payments.data ?? []).filter((item) => item.id !== editing?.id).reduce((sum, item) => sum + item.amount, 0)} onClose={() => setEditing(undefined)} onSuccess={onSuccess} onError={onError} />}{deleting && <DeleteDialog eventId={eventId} payment={deleting} onClose={() => setDeleting(null)} onSuccess={onSuccess} onError={onError} />}</section>;
}

function PaymentList({ payments, onEdit, onDelete }: { payments: EventPayment[]; onEdit: (payment: EventPayment) => void; onDelete: (payment: EventPayment) => void }) { return <div className="mt-4 overflow-hidden rounded-lg border border-border"><table className="hidden w-full text-right text-sm md:table"><thead className="bg-muted/50 text-xs text-muted-foreground"><tr>{["תאריך תשלום", "סכום", "אמצעי תשלום", "מי שילם", "הערות", "פעולות"].map((label) => <th key={label} className="px-4 py-3 font-medium">{label}</th>)}</tr></thead><tbody className="divide-y divide-border">{payments.map((payment) => <tr key={payment.id}><td className="px-4 py-3">{formatDate(payment.paidAt)}</td><td className="px-4 py-3 font-medium">{formatMoney(payment.amount)}</td><td className="px-4 py-3">{formatPaymentMethod(payment.paymentMethod)}</td><td className="px-4 py-3">{payerLabels[payment.payerType]}</td><td className="max-w-48 truncate px-4 py-3">{payment.notes || "—"}</td><td className="px-4 py-3"><Actions payment={payment} onEdit={onEdit} onDelete={onDelete} /></td></tr>)}</tbody></table><div className="divide-y divide-border md:hidden">{payments.map((payment) => <article key={payment.id} className="space-y-3 p-4"><div className="flex justify-between gap-3"><div><p className="font-medium">{formatMoney(payment.amount)}</p><p className="text-xs text-muted-foreground">{formatDate(payment.paidAt)}</p></div><Actions payment={payment} onEdit={onEdit} onDelete={onDelete} /></div><p className="text-sm">{formatPaymentMethod(payment.paymentMethod)} · {payerLabels[payment.payerType]}</p>{payment.notes && <p className="text-xs text-muted-foreground">{payment.notes}</p>}</article>)}</div></div>; }
function Actions({ payment, onEdit, onDelete }: { payment: EventPayment; onEdit: (payment: EventPayment) => void; onDelete: (payment: EventPayment) => void }) { return <div className="flex gap-1"><Button type="button" size="icon-xs" variant="ghost" onClick={() => onEdit(payment)} aria-label="עריכת תשלום"><Pencil /></Button><Button type="button" size="icon-xs" variant="ghost" onClick={() => onDelete(payment)} aria-label="מחיקת תשלום"><Trash2 className="text-destructive" /></Button></div>; }

function PaymentDialog({ eventId, payment, paymentMethods, totalDue, otherPaid, onClose, onSuccess, onError }: { eventId: string; payment: EventPayment | null; paymentMethods: string[]; totalDue: number; otherPaid: number; onClose: () => void; onSuccess: (message: string) => void; onError: (message: string) => void }) {
  const create = useCreateEventPayment(eventId); const update = useUpdateEventPayment(eventId); const options = payment?.paymentMethod && !paymentMethods.includes(payment.paymentMethod) ? [...paymentMethods, payment.paymentMethod] : paymentMethods;
  const form = useForm<EventPaymentValues>({ resolver: zodResolver(eventPaymentSchemaFor(paymentMethods, payment?.paymentMethod)), defaultValues: payment ?? { amount: 0, paymentMethod: paymentMethods[0] ?? "", payerType: "client", paidAt: new Date().toISOString().slice(0, 10), notes: "" } });
  const amount = form.watch("amount") || 0; const saving = create.isPending || update.isPending;
  const submit = async (values: EventPaymentValues) => { try { const normalized = { ...values, paidAt: new Date(`${values.paidAt}T12:00:00`).toISOString() }; if (payment) await update.mutateAsync({ id: payment.id, values: normalized }); else await create.mutateAsync(normalized); onSuccess(payment ? "התשלום עודכן בהצלחה." : "התשלום נוסף בהצלחה."); onClose(); } catch (error) { const message = error instanceof Error ? error.message : "לא ניתן לשמור את התשלום. נסו שוב."; onError(process.env.NODE_ENV === "development" ? message : "לא ניתן לשמור את התשלום. נסו שוב."); } };
  return <div className="fixed inset-0 z-60 grid place-items-center bg-slate-950/40 p-4" role="dialog" aria-modal="true"><form onSubmit={form.handleSubmit(submit)} className="w-full max-w-lg rounded-xl bg-card p-6 shadow-xl"><div className="flex items-center justify-between"><h3 className="font-semibold">{payment ? "עריכת תשלום" : "הוספת תשלום"}</h3><Button type="button" size="icon" variant="ghost" onClick={onClose} aria-label="סגירה"><X /></Button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="סכום" error={form.formState.errors.amount?.message}><input type="number" min="0.01" step="0.01" className={inputClass} {...form.register("amount", { valueAsNumber: true })} /></Field><Field label="תאריך תשלום" error={form.formState.errors.paidAt?.message}><input type="date" className={inputClass} {...form.register("paidAt", { setValueAs: (value: string) => value.slice(0, 10) })} /></Field><Field label="אמצעי תשלום" error={form.formState.errors.paymentMethod?.message}><select className={inputClass} {...form.register("paymentMethod")}><option value="">בחירת אמצעי תשלום</option>{options.map((method) => <option key={method} value={method}>{formatPaymentMethod(method)}</option>)}</select></Field><Field label="מי שילם" error={form.formState.errors.payerType?.message}><select className={inputClass} {...form.register("payerType")}><option value="client">לקוח</option><option value="venue">אולם</option></select></Field><label className="text-sm font-medium sm:col-span-2">הערות<textarea className="mt-1.5 min-h-24 w-full rounded-lg border border-input bg-background px-3 py-2" {...form.register("notes")} /></label></div>{otherPaid + amount > totalDue && <p className="mt-4 rounded-lg bg-amber-50 p-3 text-sm text-amber-800">סכום התשלומים גבוה מסכום האירוע</p>}<div className="mt-6 flex justify-end gap-2"><Button type="button" variant="outline" onClick={onClose}>ביטול</Button><Button type="submit" disabled={saving}>{saving ? "שומר..." : "שמירה"}</Button></div></form></div>;
}
function DeleteDialog({ eventId, payment, onClose, onSuccess, onError }: { eventId: string; payment: EventPayment; onClose: () => void; onSuccess: (message: string) => void; onError: (message: string) => void }) { const mutation = useDeleteEventPayment(eventId); return <div className="fixed inset-0 z-60 grid place-items-center bg-slate-950/40 p-4" role="alertdialog" aria-modal="true"><div className="w-full max-w-md rounded-xl bg-card p-6 shadow-xl"><h3 className="font-semibold">מחיקת תשלום</h3><p className="mt-2 text-sm text-muted-foreground">למחוק את התשלום בסך {formatMoney(payment.amount)}? האירוע עצמו לא יימחק.</p><div className="mt-6 flex justify-end gap-2"><Button type="button" variant="outline" onClick={onClose}>ביטול</Button><Button type="button" variant="destructive" disabled={mutation.isPending} onClick={async () => { try { await mutation.mutateAsync(payment.id); onSuccess("התשלום נמחק בהצלחה."); onClose(); } catch { onError("לא ניתן למחוק את התשלום."); } }}>מחיקת תשלום</Button></div></div></div>; }
function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <label className="text-sm font-medium">{label}{children}{error && <span className="mt-1 block text-xs text-destructive">{error}</span>}</label>; }
function Summary({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-medium">{value}</p></div>; }
function State({ children }: { children: React.ReactNode }) { return <div className="mt-4 flex min-h-20 items-center justify-center gap-2 rounded-lg border border-dashed border-border p-4 text-sm text-muted-foreground">{children}</div>; }
const inputClass = "mt-1.5 h-10 w-full rounded-lg border border-input bg-background px-3 text-sm";
