"use client";
import { useMemo,useState } from "react";import Link from "next/link";import * as XLSX from "xlsx";import { Button } from "@/components/ui/button";import { useExpenseMutations,useExpenses } from "../hooks/use-expenses";import type { ExpenseFormValues } from "../types";import { IMPORT_FIELDS,inferMapping,mapExpenseRow,possibleDuplicate,type ColumnMapping,type ImportField,validateImportRow } from "../utils/expense-import";
const labels:Record<ImportField,string>={expenseDate:"תאריך",category:"קטגוריה",supplierName:"ספק",description:"תיאור",amount:"סכום",includesVat:"כולל מע״מ",vatRate:"שיעור מע״מ",paymentMethod:"אמצעי תשלום",referenceNumber:"אסמכתא",eventId:"אירוע",notes:"הערות"};
export function ExpenseImportPage(){const [book,setBook]=useState<XLSX.WorkBook|null>(null);const [sheet,setSheet]=useState("");const [rows,setRows]=useState<unknown[][]>([]);const [mapping,setMapping]=useState<ColumnMapping>({});const [preview,setPreview]=useState<ExpenseFormValues[]>([]);const [result,setResult]=useState<{read:number;imported:number;skipped:number;duplicates:number}|null>(null);const mutation=useExpenseMutations().importRows;const existing=useExpenses();
 const load=async(file:File)=>{if(file.size>10*1024*1024){alert("הקובץ גדול מ־10MB");return;}const next=XLSX.read(await file.arrayBuffer(),{type:"array",cellDates:true});setBook(next);setSheet(next.SheetNames[0]??"");};
 const loadSheet=()=>{if(!book||!sheet)return;const matrix=XLSX.utils.sheet_to_json<unknown[]>(book.Sheets[sheet],{header:1,defval:null,raw:true});if(matrix.length<2)return;setRows(matrix);setMapping(inferMapping(matrix[0]));};
 const makePreview=()=>{const values=rows.slice(1,5001).filter(r=>r.some(v=>v!==null&&v!=="")).map(r=>mapExpenseRow(r,mapping));setPreview(values);};
 const statuses=useMemo(()=>preview.map((row,index)=>{const valid=validateImportRow(row).success;const duplicate=preview.some((other,i)=>i<index&&possibleDuplicate(row,other))||(existing.data?.expenses??[]).some(other=>possibleDuplicate(row,other));return !valid?"שגיאה":duplicate?"כפילות אפשרית":"תקין";}),[preview,existing.data]);
 const update=(index:number,patch:Partial<ExpenseFormValues>)=>setPreview(current=>current.map((row,i)=>i===index?{...row,...patch}:row));
 const run=async()=>{const valid=preview.filter(row=>validateImportRow(row).success);const imported=await mutation.mutateAsync(valid);setResult({read:preview.length,imported:imported.length,skipped:preview.length-valid.length,duplicates:statuses.filter(s=>s==="כפילות אפשרית").length});};
 const csv=()=>{const lines=["שורה,סטטוס",...statuses.map((s,i)=>`${i+2},${s}`)];const url=URL.createObjectURL(new Blob(["\ufeff"+lines.join("\n")],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="expense-import-errors.csv";a.click();URL.revokeObjectURL(url);};
 return <div className="mx-auto max-w-7xl space-y-6"><header><h2 className="text-2xl font-semibold">ייבוא הוצאות מאקסל</h2><p className="mt-1 text-sm text-muted-foreground">לא יישמר דבר לפני אישור הייבוא הסופי.</p></header><section className="rounded-xl border bg-card p-5"><label className="block text-sm font-medium">1. העלאת קובץ<input type="file" accept=".xlsx,.xls" className="mt-2 block w-full" onChange={e=>{const f=e.target.files?.[0];if(f)void load(f);}}/></label>{book&&<div className="mt-5 flex flex-wrap items-end gap-3"><label className="text-sm">2. בחירת גיליון<select className="mt-1 block h-10 rounded-lg border px-3" value={sheet} onChange={e=>setSheet(e.target.value)}>{book.SheetNames.map(s=><option key={s}>{s}</option>)}</select></label><Button onClick={loadSheet}>המשך להתאמת עמודות</Button></div>}</section>
 {rows.length>0&&preview.length===0&&<section className="rounded-xl border bg-card p-5"><h3 className="font-semibold">3. התאמת עמודות</h3><div className="mt-4 grid gap-3 sm:grid-cols-3">{IMPORT_FIELDS.map(field=><label key={field} className="text-sm">{labels[field]}<select className="mt-1 h-10 w-full rounded-lg border px-2" value={mapping[field]??""} onChange={e=>setMapping(m=>({...m,[field]:e.target.value===""?undefined:Number(e.target.value)}))}><option value="">לא ממופה</option>{rows[0].map((h,i)=><option key={i} value={i}>{String(h??`עמודה ${i+1}`)}</option>)}</select></label>)}</div><Button className="mt-5" onClick={makePreview}>יצירת תצוגה מקדימה</Button></section>}
 {preview.length>0&&!result&&<section className="space-y-4"><div className="flex items-center justify-between"><h3 className="font-semibold">4. תצוגה מקדימה ({preview.length} שורות)</h3><Button disabled={mutation.isPending} onClick={run}>{mutation.isPending?"מייבא...":"5. ייבוא"}</Button></div><div className="overflow-x-auto rounded-xl border bg-card"><table className="w-full min-w-[900px] text-sm"><thead><tr>{["סטטוס","תאריך","קטגוריה","ספק","תיאור","סכום","אסמכתא"].map(h=><th className="p-2 text-right" key={h}>{h}</th>)}</tr></thead><tbody>{preview.map((row,i)=><tr key={i} className="border-t"><td className={`p-2 ${statuses[i]==="תקין"?"text-emerald-700":statuses[i]==="כפילות אפשרית"?"text-amber-700":"text-red-700"}`}>{statuses[i]}</td><td><input type="date" value={row.expenseDate} onChange={e=>update(i,{expenseDate:e.target.value})} className="m-1 h-9 border px-2"/></td><td><input value={row.category} onChange={e=>update(i,{category:e.target.value})} className="m-1 h-9 border px-2"/></td><td><input value={row.supplierName} onChange={e=>update(i,{supplierName:e.target.value})} className="m-1 h-9 border px-2"/></td><td><input value={row.description} onChange={e=>update(i,{description:e.target.value})} className="m-1 h-9 border px-2"/></td><td><input type="number" value={Number.isFinite(row.amount)?row.amount:""} onChange={e=>update(i,{amount:e.target.value===""?Number.NaN:Number(e.target.value)})} className="m-1 h-9 w-28 border px-2"/></td><td><input value={row.referenceNumber} onChange={e=>update(i,{referenceNumber:e.target.value})} className="m-1 h-9 border px-2"/></td></tr>)}</tbody></table></div></section>}
 {result&&<section className="rounded-xl border bg-card p-6"><h3 className="font-semibold">תוצאות הייבוא</h3><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4"><span>שורות שנקראו: {result.read}</span><span>הוצאות שיובאו: {result.imported}</span><span>שורות שדולגו: {result.skipped}</span><span>כפילויות: {result.duplicates}</span></div><div className="mt-5 flex gap-2"><Button variant="outline" onClick={csv}>דוח שגיאות CSV</Button><Link href="/expenses" className="inline-flex h-8 items-center rounded-lg bg-black px-2.5 text-sm font-medium text-white">חזרה להוצאות</Link></div></section>}</div>}
