"use client";
import Link from "next/link";
import { useMemo,useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Button } from "@/components/ui/button";
import { formatDate,formatMoney } from "@/lib/hebrew";
import { calculateExpenseVat } from "../utils/expense-calculations";
import { useExpenseMutations,useExpenses } from "../hooks/use-expenses";
import { EXPENSE_CATEGORIES,type Expense,type ExpenseFormValues } from "../types";
import { expenseSchema } from "../validation";

const currentMonth=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;};
const empty:ExpenseFormValues={expenseDate:new Date().toLocaleDateString("sv-SE",{timeZone:"Asia/Jerusalem"}),category:"",supplierName:"",description:"",amount:0,includesVat:true,vatRate:18,paymentMethod:"",referenceNumber:"",eventId:"",notes:""};
const input="h-10 w-full rounded-lg border border-input bg-background px-3 text-sm";
export function ExpensesPage(){ const query=useExpenses(); const mutations=useExpenseMutations(); const [month,setMonth]=useState(currentMonth); const [category,setCategory]=useState(""); const [supplier,setSupplier]=useState(""); const [editing,setEditing]=useState<Expense|null>(null); const [open,setOpen]=useState(false); const [message,setMessage]=useState("");
 const filtered=useMemo(()=>(query.data?.expenses??[]).filter(e=>(!month||e.expenseDate.startsWith(month))&&(!category||e.category===category)&&(!supplier||e.supplierName.includes(supplier))),[query.data,month,category,supplier]);
 const totals=filtered.reduce((sum,e)=>{const c=calculateExpenseVat(e.amount,e.includesVat,e.vatRate);return {gross:sum.gross+c.gross,net:sum.net+c.net,vat:sum.vat+c.vat};},{gross:0,net:0,vat:0});
 const remove=async(e:Expense)=>{if(!window.confirm("למחוק את ההוצאה?"))return;try{await mutations.remove.mutateAsync(e.id);setMessage("ההוצאה נמחקה.");}catch(error){setMessage(error instanceof Error?error.message:"המחיקה נכשלה");}};
 if(query.isLoading)return <State text="טוען הוצאות..."/>; if(query.isError||!query.data)return <State text="לא ניתן לטעון את ההוצאות" retry={()=>query.refetch()}/>;
 return <div className="mx-auto max-w-7xl space-y-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-2xl font-semibold">הוצאות</h2><p className="mt-1 text-sm text-muted-foreground">ניהול הוצאות תפעוליות וחשבוניות ספקים.</p></div><div className="flex gap-2"><Link href="/expenses/import" className="inline-flex h-8 items-center rounded-lg border border-border bg-background px-2.5 text-sm font-medium hover:bg-muted">ייבוא הוצאות מאקסל</Link><Button onClick={()=>{setEditing(null);setOpen(true);}}>הוספת הוצאה</Button></div></header>
 {message&&<div role="status" className="rounded-lg border bg-card px-4 py-3 text-sm">{message}</div>}
 <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Kpi label="הוצאות החודש" value={formatMoney(totals.gross)}/><Kpi label="הוצאות לפני מע״מ" value={formatMoney(totals.net)}/><Kpi label="מע״מ תשומות משוער" value={formatMoney(totals.vat)}/><Kpi label="מספר הוצאות" value={String(filtered.length)}/></div>
 <section className="grid gap-3 rounded-xl border bg-card p-4 sm:grid-cols-3"><label className="text-sm">חודש<input type="month" className={`${input} mt-1`} value={month} onChange={e=>setMonth(e.target.value)}/></label><label className="text-sm">קטגוריה<select className={`${input} mt-1`} value={category} onChange={e=>setCategory(e.target.value)}><option value="">הכל</option>{EXPENSE_CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></label><label className="text-sm">ספק<input className={`${input} mt-1`} value={supplier} onChange={e=>setSupplier(e.target.value)} placeholder="חיפוש ספק"/></label></section>
 <div className="overflow-x-auto rounded-xl border bg-card"><table className="w-full min-w-[900px] text-sm"><thead className="bg-muted"><tr>{["תאריך","קטגוריה","ספק","תיאור","סכום","כולל מע״מ","אמצעי תשלום","אירוע מקושר","פעולות"].map(h=><th key={h} className="p-3 text-right">{h}</th>)}</tr></thead><tbody>{filtered.map(e=><tr key={e.id} className="border-t"><td className="p-3">{formatDate(e.expenseDate)}</td><td className="p-3">{e.category}</td><td className="p-3">{e.supplierName||"—"}</td><td className="p-3">{e.description||"—"}</td><td className="p-3 font-medium">{formatMoney(calculateExpenseVat(e.amount,e.includesVat,e.vatRate).gross)}</td><td className="p-3">{e.includesVat?"כן":"לא"}</td><td className="p-3">{e.paymentMethod||"—"}</td><td className="p-3">{query.data.events.find(x=>x.id===e.eventId)?.label??"—"}</td><td className="p-3"><div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>{setEditing(e);setOpen(true);}}>עריכה</Button><Button size="sm" variant="destructive" onClick={()=>remove(e)}>מחיקה</Button></div></td></tr>)}</tbody></table>{!filtered.length&&<div className="p-10 text-center text-muted-foreground">לא נמצאו הוצאות</div>}</div>
 {open&&<ExpenseDialog expense={editing} events={query.data.events} onClose={()=>setOpen(false)} onSaved={text=>{setMessage(text);setOpen(false);}}/>}</div>;
}
function ExpenseDialog({expense,events,onClose,onSaved}:{expense:Expense|null;events:{id:string;label:string}[];onClose:()=>void;onSaved:(text:string)=>void}){const {create,update}=useExpenseMutations();const form=useForm<ExpenseFormValues>({resolver:zodResolver(expenseSchema),defaultValues:expense??empty});const pending=create.isPending||update.isPending;const submit=async(values:ExpenseFormValues)=>{try{if(expense)await update.mutateAsync({id:expense.id,values});else await create.mutateAsync(values);onSaved(expense?"ההוצאה עודכנה.":"ההוצאה נוספה.");}catch(error){form.setError("root",{message:error instanceof Error?error.message:"השמירה נכשלה"});}};return <div className="fixed inset-0 z-[100] overflow-y-auto bg-black/50 p-4"><form onSubmit={form.handleSubmit(submit)} className="mx-auto max-w-2xl rounded-xl bg-card p-6"><h3 className="text-lg font-semibold">{expense?"עריכת הוצאה":"הוספת הוצאה"}</h3><div className="mt-5 grid gap-4 sm:grid-cols-2"><F label="תאריך" error={form.formState.errors.expenseDate?.message}><input type="date" className={input} {...form.register("expenseDate")}/></F><F label="קטגוריה" error={form.formState.errors.category?.message}><select className={input} {...form.register("category")}><option value="">בחרו</option>{EXPENSE_CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></F><F label="ספק"><input className={input} {...form.register("supplierName")}/></F><F label="תיאור"><input className={input} {...form.register("description")}/></F><F label="סכום" error={form.formState.errors.amount?.message}><input type="number" min="0.01" step="0.01" className={input} {...form.register("amount",{valueAsNumber:true})}/></F><F label="שיעור מע״מ"><input type="number" min="0" step="0.01" className={input} {...form.register("vatRate",{valueAsNumber:true})}/></F><label className="flex items-center gap-2 text-sm"><input type="checkbox" {...form.register("includesVat")}/>כולל מע״מ</label><F label="אמצעי תשלום"><input className={input} {...form.register("paymentMethod")}/></F><F label="אסמכתא"><input className={input} {...form.register("referenceNumber")}/></F><F label="אירוע מקושר"><select className={input} {...form.register("eventId")}><option value="">ללא</option>{events.map(e=><option key={e.id} value={e.id}>{e.label}</option>)}</select></F><F label="הערות"><textarea className="min-h-20 w-full rounded-lg border p-3" {...form.register("notes")}/></F></div>{form.formState.errors.root&&<p className="mt-3 text-sm text-destructive">{form.formState.errors.root.message}</p>}<div className="mt-6 flex justify-end gap-2"><Button type="button" variant="outline" onClick={onClose}>ביטול</Button><Button disabled={pending}>{pending?"שומר...":"שמירה"}</Button></div></form></div>}
function F({label,error,children}:{label:string;error?:string;children:React.ReactNode}){return <label className="text-sm">{label}<div className="mt-1">{children}</div>{error&&<span className="text-xs text-destructive">{error}</span>}</label>};function Kpi({label,value}:{label:string;value:string}){return <div className="rounded-xl border bg-card p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-lg font-semibold">{value}</p></div>};function State({text,retry}:{text:string;retry?:()=>void}){return <div className="grid min-h-80 place-items-center"><div className="text-center"><p>{text}</p>{retry&&<Button className="mt-3" onClick={retry}>נסה שוב</Button>}</div></div>}
