"use client";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";

type Row = { id: string; notification_type: string; scheduled_for: string | null; sent_at: string | null; status: string; error_message: string | null; employees: { full_name: string } | null; events: { client_name: string } | null };
const statusLabels: Record<string, string> = { pending: "ממתין", processing: "בתהליך", sent: "נשלח", delivered: "נמסר", read: "נקרא", failed: "נכשל", cancelled: "בוטל" };
const typeLabels: Record<string, string> = { assignment_created: "שיבוץ חדש", event_changed: "שינוי באירוע", reminder_day_before: "תזכורת יום לפני", reminder_hours_before: "תזכורת לפני האירוע", work_time_updated: "סיכום שעות" };
async function load(): Promise<Row[]> { const response = await fetch("/api/whatsapp/notifications"); const body = await response.json(); if (!response.ok) throw new Error(body.error); return body; }

export function WhatsAppNotificationsPage() {
  const client = useQueryClient(); const query = useQuery({ queryKey: ["whatsapp-notifications"], queryFn: load });
  const retry = useMutation({ mutationFn: async (id: string) => { const response = await fetch("/api/whatsapp/notifications", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id }) }); if (!response.ok) throw new Error("הניסיון החוזר נכשל"); }, onSuccess: () => client.invalidateQueries({ queryKey: ["whatsapp-notifications"] }) });
  return <div className="mx-auto max-w-7xl space-y-5"><div><h2 className="text-2xl font-semibold">יומן התראות WhatsApp</h2><p className="mt-2 text-sm text-muted-foreground">סטטוס השליחה והודעות ספק השירות.</p></div>{query.isLoading ? <p>טוען...</p> : query.isError ? <p className="text-destructive">לא ניתן לטעון את יומן ההתראות.</p> : <div className="overflow-x-auto rounded-xl border border-border bg-card"><table className="w-full min-w-200 text-right text-sm"><thead className="bg-muted/50"><tr>{["עובד", "אירוע", "סוג התראה", "מועד מתוכנן", "מועד שליחה", "סטטוס", "שגיאה", "פעולות"].map((label) => <th key={label} className="px-4 py-3">{label}</th>)}</tr></thead><tbody>{query.data?.map((row) => <tr key={row.id} className="border-t border-border"><td className="px-4 py-3">{row.employees?.full_name ?? "—"}</td><td className="px-4 py-3">{row.events?.client_name ?? "בדיקה"}</td><td className="px-4 py-3">{typeLabels[row.notification_type] ?? row.notification_type}</td><td className="px-4 py-3">{row.scheduled_for ? formatDateTime(row.scheduled_for) : "—"}</td><td className="px-4 py-3">{row.sent_at ? formatDateTime(row.sent_at) : "—"}</td><td className="px-4 py-3">{statusLabels[row.status] ?? row.status}</td><td className="max-w-72 px-4 py-3 text-xs text-destructive">{row.error_message ?? "—"}</td><td className="px-4 py-3">{row.status === "failed" && <Button size="sm" variant="outline" disabled={retry.isPending} onClick={() => retry.mutate(row.id)}>נסה שוב</Button>}</td></tr>)}</tbody></table></div>}</div>;
}
function formatDateTime(value: string) { return new Intl.DateTimeFormat("he-IL", { timeZone: "Asia/Jerusalem", dateStyle: "short", timeStyle: "short" }).format(new Date(value)); }
