"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import type { WhatsAppSettings } from "@/lib/whatsapp/types";

type Employee = { id: string; full_name: string; phone: string | null };
const defaults: WhatsAppSettings = { enabled: false, assignmentEnabled: true, eventChangeEnabled: true, dayBeforeEnabled: true, hoursBeforeEnabled: true, hoursBefore: 4, workTimeEnabled: true, salaryInOwnerMessages: false };

export function WhatsAppSettingsCard() {
  const [settings, setSettings] = useState(defaults); const [employees, setEmployees] = useState<Employee[]>([]); const [employeeId, setEmployeeId] = useState(""); const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => { void fetch("/api/whatsapp/settings").then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error); setSettings(body.settings); setEmployees(body.employees); }).catch((error) => setNotice(error instanceof Error ? error.message : "טעינת ההגדרות נכשלה")).finally(() => setLoading(false)); }, []);
  const save = async () => { setNotice(""); const response = await fetch("/api/whatsapp/settings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(settings) }); const body = await response.json(); setNotice(response.ok ? "הגדרות WhatsApp נשמרו." : body.error); };
  const test = async () => { setNotice(""); const response = await fetch("/api/whatsapp/settings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ employeeId }) }); const body = await response.json(); setNotice(response.ok ? "הודעת הבדיקה נוספה לתור ומסומנת כמצב בדיקה." : body.error); };
  if (loading) return <div className="rounded-xl border border-border bg-card p-6">טוען הגדרות WhatsApp...</div>;
  return <section className="rounded-xl border border-border bg-card p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">התראות WhatsApp</h3><p className="mt-1 text-xs text-muted-foreground">השליחה מתבצעת דרך Meta WhatsApp Cloud API בלבד.</p></div><Link href="/settings/whatsapp-notifications" className="text-sm text-primary hover:underline">יומן התראות</Link></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{[["enabled", "הפעלת התראות WhatsApp"], ["assignmentEnabled", "שליחת הודעה בעת שיבוץ"], ["eventChangeEnabled", "שליחת הודעה בעת שינוי תאריך או שעה"], ["dayBeforeEnabled", "תזכורת יום לפני"], ["hoursBeforeEnabled", "תזכורת מספר שעות לפני האירוע"], ["workTimeEnabled", "שליחת סיכום שעות לאחר הזנה"], ["salaryInOwnerMessages", "כלילת שכר בהודעה שנוצרה על ידי בעלים"]].map(([key, label]) => <label key={key} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={Boolean(settings[key as keyof WhatsAppSettings])} onChange={(event) => setSettings((current) => ({ ...current, [key]: event.target.checked }))} />{label}</label>)}<label className="text-sm">מספר שעות לפני האירוע<input type="number" min="1" max="72" value={settings.hoursBefore} onChange={(event) => setSettings((current) => ({ ...current, hoursBefore: Number(event.target.value) }))} className="mt-1.5 h-10 w-full rounded-lg border border-input bg-background px-3" /></label></div><div className="mt-5 flex flex-wrap gap-2"><Button type="button" onClick={save}>שמירת הגדרות WhatsApp</Button></div><div className="mt-6 rounded-lg border border-dashed border-border p-4"><p className="text-sm font-medium">שליחת הודעת בדיקה</p><p className="mt-1 text-xs text-muted-foreground">מצב בדיקה — ההודעה תישלח רק לעובד שנבחר ורק כאשר ההתראות פעילות.</p><div className="mt-3 flex flex-col gap-2 sm:flex-row"><select value={employeeId} onChange={(event) => setEmployeeId(event.target.value)} className="h-10 flex-1 rounded-lg border border-input bg-background px-3"><option value="">בחירת עובד</option>{employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.full_name}{employee.phone ? "" : " — חסר טלפון"}</option>)}</select><Button type="button" variant="outline" disabled={!employeeId} onClick={test}>שליחת הודעת בדיקה</Button></div></div>{notice && <p className="mt-4 text-sm">{notice}</p>}</section>;
}
