import type { EventPayment, EventPaymentValues } from "../types";
type PaymentRow = { id: string; event_id: string; amount: number | string; payment_method: string; payer_type: EventPaymentValues["payerType"]; paid_at: string; notes: string | null; created_at: string; updated_at: string };
const toPayment = (row: PaymentRow): EventPayment => ({ id: row.id, eventId: row.event_id, amount: Number(row.amount), paymentMethod: row.payment_method, payerType: row.payer_type, paidAt: row.paid_at.slice(0, 10), notes: row.notes ?? "", createdAt: row.created_at, updatedAt: row.updated_at });
export const buildEventPaymentPayload = (values: EventPaymentValues) => ({ amount: values.amount, payment_method: values.paymentMethod, payer_type: values.payerType, paid_at: values.paidAt, notes: values.notes.trim() || null });
async function api<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, { ...init, headers: { "Content-Type": "application/json", ...init?.headers } }); if (!response.ok) { const body = await response.json().catch(() => null) as { error?: string } | null; const message = body?.error ?? (response.status === 403 ? "Unauthorized" : "Payment request failed"); if (process.env.NODE_ENV === "development") console.error("Event payment request failed:", message); throw new Error(message); } return response.status === 204 ? undefined as T : response.json() as Promise<T>; }
export async function listEventPayments(eventId: string) { return (await api<PaymentRow[]>(`/api/event-payments?eventId=${encodeURIComponent(eventId)}`)).map(toPayment); }
export async function createEventPayment(eventId: string, values: EventPaymentValues) { return toPayment(await api<PaymentRow>("/api/event-payments", { method: "POST", body: JSON.stringify({ eventId, values: buildEventPaymentPayload(values) }) })); }
export async function updateEventPayment(id: string, values: EventPaymentValues) { return toPayment(await api<PaymentRow>("/api/event-payments", { method: "PATCH", body: JSON.stringify({ id, values: buildEventPaymentPayload(values) }) })); }
export async function deleteEventPayment(id: string) { await api<void>(`/api/event-payments?id=${encodeURIComponent(id)}`, { method: "DELETE" }); }
