"use client";

import { useState } from "react";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { flexRender, getCoreRowModel, useReactTable, type ColumnDef } from "@tanstack/react-table";
import { LoaderCircle, Pencil, Plus, Trash2, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { formatDate, translateStoredValue } from "@/lib/hebrew";
import { useCreateMasterData, useDeleteMasterData, useMasterData, useUpdateMasterData } from "../hooks/use-master-data";
import type { MasterDataInput, MasterDataKind, MasterDataRecord } from "../types";
import { masterDataConfig } from "../types";
import { masterDataSchema } from "../validation";

export function MasterDataPage({ kind }: { kind: MasterDataKind }) {
  const config = masterDataConfig[kind];
  const query = useMasterData(kind);
  const [editing, setEditing] = useState<MasterDataRecord | null | undefined>(undefined);
  const [deleting, setDeleting] = useState<MasterDataRecord | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  if (query.isLoading) return <Loading title={config.title} />;
  if (query.isError) return <State title={config.title} message="לא ניתן לטעון את הנתונים. בדקו את ההרשאות ונסו שוב." />;
  return <div className="mx-auto max-w-5xl space-y-6"><header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-muted-foreground">הגדרות</p><h2 className="mt-1 text-2xl font-semibold tracking-tight">{config.title}</h2><p className="mt-2 text-sm text-muted-foreground">{config.description}</p></div><Button type="button" onClick={() => setEditing(null)}><Plus data-icon="inline-start" />{config.singular} חדש</Button></header>{notice && <div role="status" className="fixed bottom-5 left-5 z-60 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800 shadow-lg">{notice}</div>}<MasterDataTable data={query.data ?? []} onEdit={setEditing} onDelete={setDeleting} />{editing !== undefined && <MasterDataForm kind={kind} record={editing} onClose={() => setEditing(undefined)} onSuccess={(message) => setNotice(message)} />}{deleting && <DeleteDialog kind={kind} record={deleting} onClose={() => setDeleting(null)} onSuccess={(message) => setNotice(message)} />}</div>;
}

function MasterDataTable({ data, onEdit, onDelete }: { data: MasterDataRecord[]; onEdit: (row: MasterDataRecord) => void; onDelete: (row: MasterDataRecord) => void }) {
  const showColor = data.some((row) => row.colorHex !== undefined);
  const columns: ColumnDef<MasterDataRecord>[] = [{ accessorKey: "name", header: "שם", cell: ({ row }) => <span className="flex items-center gap-2">{row.original.colorHex && <span className="size-4 rounded-full border border-black/10" style={{ backgroundColor: row.original.colorHex }} />}{translateStoredValue(row.original.name)}</span> }, ...(showColor ? [{ id: "color", header: "צבע", cell: ({ row }: { row: { original: MasterDataRecord } }) => row.original.colorHex ?? "—" } as ColumnDef<MasterDataRecord>] : []), { accessorKey: "createdAt", header: "נוצר בתאריך", cell: ({ row }) => formatDate(row.original.createdAt) }, { id: "actions", header: "", cell: ({ row }) => <div className="flex justify-end gap-1"><Button type="button" size="icon-xs" variant="ghost" onClick={() => onEdit(row.original)} aria-label={`עריכת ${row.original.name}`}><Pencil /></Button><Button type="button" size="icon-xs" variant="ghost" onClick={() => onDelete(row.original)} aria-label={`מחיקת ${row.original.name}`}><Trash2 className="text-destructive" /></Button></div> }];
  const table = useReactTable({ data, columns, getCoreRowModel: getCoreRowModel() });
  if (!data.length) return <State title="עדיין אין רשומות" message="צרו את הרשומה הראשונה כדי שתהיה זמינה במערכת." />;
  return <div className="overflow-hidden rounded-xl border border-border bg-card shadow-sm"><table className="w-full text-left text-sm"><thead className="bg-muted/50 text-xs text-muted-foreground">{table.getHeaderGroups().map((group) => <tr key={group.id}>{group.headers.map((header) => <th className="px-5 py-3.5 font-medium" key={header.id}>{flexRender(header.column.columnDef.header, header.getContext())}</th>)}</tr>)}</thead><tbody className="divide-y divide-border">{table.getRowModel().rows.map((row) => <tr key={row.id} className="hover:bg-muted/30">{row.getVisibleCells().map((cell) => <td className="px-5 py-4" key={cell.id}>{flexRender(cell.column.columnDef.cell, cell.getContext())}</td>)}</tr>)}</tbody></table></div>;
}

function MasterDataForm({ kind, record, onClose, onSuccess }: { kind: MasterDataKind; record: MasterDataRecord | null; onClose: () => void; onSuccess: (message: string) => void }) {
  const config = masterDataConfig[kind]; const create = useCreateMasterData(kind); const update = useUpdateMasterData(kind); const form = useForm<MasterDataInput>({ resolver: zodResolver(masterDataSchema), defaultValues: { name: record?.name ?? "", colorHex: kind === "event_types" ? record?.colorHex ?? "#475569" : undefined } }); const saving = create.isPending || update.isPending;
  const submit = async (input: MasterDataInput) => { try { if (record) await update.mutateAsync({ id: record.id, input }); else await create.mutateAsync(input); onSuccess(`${config.singular} ${record ? "עודכן" : "נוצר"} בהצלחה.`); onClose(); } catch { form.setError("name", { message: "לא ניתן לשמור. ייתכן שהשם כבר קיים." }); } };
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4" role="dialog" aria-modal="true"><form onSubmit={form.handleSubmit(submit)} className="w-full max-w-md rounded-xl bg-card p-6 shadow-xl"><div className="flex items-center justify-between"><h3 className="font-semibold">{record ? `עריכת ${config.singular}` : `${config.singular} חדש`}</h3><Button type="button" variant="ghost" size="icon" onClick={onClose} aria-label="סגירה"><X /></Button></div><label className="mt-5 block text-sm font-medium">שם<input autoFocus className="mt-1.5 h-9 w-full rounded-lg border border-input bg-background px-3 text-sm outline-none focus:ring-3 focus:ring-ring/20" {...form.register("name")} /></label>{form.formState.errors.name && <p className="mt-1 text-xs text-destructive">{form.formState.errors.name.message}</p>}{kind === "event_types" && <label className="mt-5 block text-sm font-medium">צבע<div className="mt-1.5 flex items-center gap-3"><input type="color" className="h-10 w-14 cursor-pointer rounded border border-input bg-background p-1" {...form.register("colorHex")} /><input className="h-10 flex-1 rounded-lg border border-input bg-background px-3 font-mono text-sm" {...form.register("colorHex")} /></div>{form.formState.errors.colorHex && <span className="mt-1 block text-xs text-destructive">{form.formState.errors.colorHex.message}</span>}</label>}<div className="mt-6 flex justify-end gap-2"><Button type="button" variant="outline" onClick={onClose}>ביטול</Button><Button type="submit" disabled={saving}>{saving ? "שומר..." : "שמירה"}</Button></div></form></div>;
}

function DeleteDialog({ kind, record, onClose, onSuccess }: { kind: MasterDataKind; record: MasterDataRecord; onClose: () => void; onSuccess: (message: string) => void }) { const mutation = useDeleteMasterData(kind); const singular = masterDataConfig[kind].singular; const remove = async () => { try { await mutation.mutateAsync(record.id); onSuccess(`${singular} נמחק בהצלחה.`); onClose(); } catch { onClose(); } }; return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4" role="dialog" aria-modal="true"><div className="w-full max-w-md rounded-xl bg-card p-6 shadow-xl"><h3 className="font-semibold">מחיקת {singular}?</h3><p className="mt-2 text-sm text-muted-foreground">פעולה זו תמחק לצמיתות את “{translateStoredValue(record.name)}”. רשומות שכבר משתמשות בו עלולות להיות מושפעות.</p><div className="mt-6 flex justify-end gap-2"><Button type="button" variant="outline" onClick={onClose}>ביטול</Button><Button type="button" variant="destructive" disabled={mutation.isPending} onClick={remove}>{mutation.isPending ? "מוחק..." : "מחיקה"}</Button></div></div></div>; }
function Loading({ title }: { title: string }) { return <div className="grid min-h-80 place-items-center"><span className="flex items-center gap-2 text-sm text-muted-foreground"><LoaderCircle className="size-4 animate-spin" />טוען {title}...</span></div>; }
function State({ title, message }: { title: string; message: string }) { return <div className="grid min-h-80 place-items-center rounded-xl border border-dashed border-border bg-card p-8 text-center"><div><p className="font-medium">{title}</p><p className="mt-1 text-sm text-muted-foreground">{message}</p></div></div>; }
