"use client";
import { useState } from "react";
import * as XLSX from "xlsx";
import { useQueryClient } from "@tanstack/react-query";
import { FileSpreadsheet, LoaderCircle, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { formatMoney, payerLabels, translateStoredValue } from "@/lib/hebrew";
import { importEventRows } from "./services";
import type { BulkDefaults, ImportMasterData, ImportRow } from "./types";
import { hasBlockingErrors, validateImportRow, workbookRows } from "./utils";

const defaults: BulkDefaults = { venueId: "", startTime: "19:30", pricePerGuest: 15, packageType: "Pouring", payerType: "client" };
const inputClass = "h-9 w-full min-w-28 rounded-md border border-input bg-background px-2 text-sm";

export function EventImportDialog({ master, onClose, onSuccess, onError }: { master: ImportMasterData; onClose: () => void; onSuccess: (message: string) => void; onError: (message: string) => void }) {
  const client = useQueryClient();
  const [rows, setRows] = useState<ImportRow[]>([]);
  const [bulk, setBulk] = useState<BulkDefaults>({ ...defaults, venueId: master.venues.find((venue) => venue.name.trim() === "קסנאדו")?.id ?? "" });
  const [reading, setReading] = useState(false);
  const [saving, setSaving] = useState(false);
  const updateRows = (next: ImportRow[]) => setRows(next.map((row) => validateImportRow(row, master)));
  const updatePreviewRow = (rowNumber: number, patch: Partial<ImportRow>) => updateRows(rows.map((row) => row.rowNumber === rowNumber ? { ...row, ...patch } : row));
  const applyBulk = <K extends keyof BulkDefaults>(key: K) => { const selected = bulk[key]; updateRows(rows.map((row) => ({ ...row, [key]: selected, ...(key === "venueId" ? { venueName: master.venues.find((venue) => venue.id === selected)?.name ?? "" } : {}) }))); };
  const readFile = async (file: File) => { setReading(true); try { const workbook = XLSX.read(await file.arrayBuffer(), { type: "array", cellDates: true }); setRows(workbookRows(workbook, XLSX.utils.sheet_to_json, master)); } catch { onError("לא ניתן לקרוא את חוברת העבודה."); } finally { setReading(false); } };
  const submit = async () => { const validated = rows.map((row) => validateImportRow(row, master)); setRows(validated); const validRows = validated.filter((row) => !hasBlockingErrors(row)); if (!validRows.length) return onError("לא ניתן לייבא: אין שורות תקינות לייבוא."); setSaving(true); try { await importEventRows(validRows); await client.invalidateQueries({ queryKey: ["events"] }); const skipped = validated.length - validRows.length; onSuccess(`${validRows.length} אירועים יובאו בהצלחה${skipped ? `; ${skipped} שורות לא תקינות דולגו` : ""}.`); onClose(); } catch { onError("ייבוא האירועים נכשל. לא נוצרו אולמות או חבילות חדשות."); } finally { setSaving(false); } };
  return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/50 p-3 sm:p-6" role="dialog" aria-modal="true"><div className="mx-auto max-w-7xl rounded-xl bg-card shadow-xl"><header className="sticky top-0 z-10 flex items-center justify-between border-b border-border bg-card px-5 py-4"><div><h2 className="font-semibold">ייבוא אירועים מחוברת עבודה</h2><p className="mt-1 text-sm text-muted-foreground">העלו Excel, בדקו את הערכים ושנו אותם לפני הייבוא.</p></div><Button type="button" size="icon" variant="ghost" onClick={onClose} aria-label="סגירה"><X /></Button></header><div className="space-y-5 p-5"><FilePicker reading={reading} onFile={readFile} />{rows.length > 0 && <><BulkControls bulk={bulk} master={master} onChange={setBulk} onApply={applyBulk} /><Preview rows={rows} master={master} updateRow={updatePreviewRow} /></>}<footer className="flex justify-end gap-2 border-t border-border pt-5"><Button type="button" variant="outline" onClick={onClose}>ביטול</Button><Button type="button" disabled={!rows.length || saving} onClick={() => void submit()}>{saving ? "מייבא..." : `ייבוא ${rows.length || ""} אירועים`}</Button></footer></div></div></div>;
}

function FilePicker({ reading, onFile }: { reading: boolean; onFile: (file: File) => Promise<void> }) { return <><label className="flex min-h-28 cursor-pointer flex-col items-center justify-center rounded-xl border border-dashed border-border p-5 text-center"><FileSpreadsheet className="size-7 text-muted-foreground" /><span className="mt-2 text-sm font-medium">בחירת קובץ Excel</span><span className="text-xs text-muted-foreground">xlsx, xls או csv</span><input type="file" accept=".xlsx,.xls,.csv" className="sr-only" onChange={(event) => { const file = event.target.files?.[0]; if (file) void onFile(file); }} /></label>{reading && <p className="flex items-center justify-center gap-2 text-sm"><LoaderCircle className="size-4 animate-spin" />קורא את הקובץ...</p>}</>; }
function Preview({ rows, master, updateRow }: { rows: ImportRow[]; master: ImportMasterData; updateRow: (rowNumber: number, patch: Partial<ImportRow>) => void }) { return <><div className="hidden overflow-x-auto rounded-xl border border-border md:block"><table className="w-full min-w-[1500px] text-right text-sm"><thead className="bg-muted/50 text-xs text-muted-foreground"><tr>{["שורה", "תאריך", "איש קשר", "אורחים", "סוג אירוע", "אולם", "שעה", "מחיר לאורח", "הכנסה צפויה", "חבילת בר", "מי משלם", "בדיקה"].map((label) => <th key={label} className="px-3 py-3 font-medium">{label}</th>)}</tr></thead><tbody className="divide-y divide-border">{rows.map((row) => <tr key={row.rowNumber} className={hasBlockingErrors(row) ? "bg-red-50/60" : row.errors.length ? "bg-amber-50/60" : ""}><td className="px-3 py-3">{row.rowNumber}</td><td className="px-3 py-3">{row.eventDate}</td><td className="px-3 py-3">{row.clientName || "—"}</td><td className="px-3 py-3"><GuestInput row={row} updateRow={updateRow} /></td><td className="px-3 py-3"><EventTypeSelect row={row} master={master} updateRow={updateRow} /></td><td className="px-3 py-3"><VenueSelect row={row} master={master} updateRow={updateRow} /></td><td className="px-3 py-3"><input type="time" className={inputClass} value={row.startTime} onChange={(event) => updateRow(row.rowNumber, { startTime: event.target.value })} /></td><td className="px-3 py-3"><input type="number" min="0" step="0.01" className={inputClass} value={row.pricePerGuest} onChange={(event) => updateRow(row.rowNumber, { pricePerGuest: event.target.valueAsNumber })} /></td><td className="px-3 py-3 font-medium">{formatMoney((row.guestCount ?? 0) * row.pricePerGuest)}</td><td className="px-3 py-3"><PackageSelect row={row} master={master} updateRow={updateRow} /></td><td className="px-3 py-3"><PayerSelect row={row} updateRow={updateRow} /></td><td className="max-w-64 px-3 py-3"><Errors row={row} /></td></tr>)}</tbody></table></div><div className="space-y-3 md:hidden">{rows.map((row) => <article key={row.rowNumber} className={`rounded-xl border p-4 ${hasBlockingErrors(row) ? "border-red-300 bg-red-50/60" : "border-border"}`}><p className="font-medium">{row.eventName || `שורה ${row.rowNumber}`}</p><div className="mt-4 grid gap-3"><Label text="מספר אורחים"><GuestInput row={row} updateRow={updateRow} /></Label><Label text="סוג אירוע"><EventTypeSelect row={row} master={master} updateRow={updateRow} /></Label><p className="text-sm">הכנסה צפויה: <strong>{formatMoney((row.guestCount ?? 0) * row.pricePerGuest)}</strong></p><Errors row={row} /></div></article>)}</div></>; }
function GuestInput({ row, updateRow }: { row: ImportRow; updateRow: (id: number, patch: Partial<ImportRow>) => void }) { return <input type="number" min="1" step="1" className={inputClass} value={row.guestCount ?? ""} onChange={(event) => updateRow(row.rowNumber, { guestCount: event.target.value === "" ? null : event.target.valueAsNumber })} />; }
function EventTypeSelect({ row, master, updateRow }: { row: ImportRow; master: ImportMasterData; updateRow: (id: number, patch: Partial<ImportRow>) => void }) { return <select className={inputClass} value={row.eventType} onChange={(event) => updateRow(row.rowNumber, { eventType: event.target.value, eventTypeNeedsReview: false, errors: row.errors.filter((error) => !error.includes("סוג האירוע הוסק")) })}>{master.eventTypes.map((type) => <option key={type} value={type}>{translateStoredValue(type)}</option>)}</select>; }
function VenueSelect({ row, master, updateRow }: { row: ImportRow; master: ImportMasterData; updateRow: (id: number, patch: Partial<ImportRow>) => void }) { return <select className={inputClass} value={row.venueId} onChange={(event) => updateRow(row.rowNumber, { venueId: event.target.value, venueName: master.venues.find((venue) => venue.id === event.target.value)?.name ?? "" })}><option value="">האולם אינו קיים</option>{master.venues.map((venue) => <option key={venue.id} value={venue.id}>{venue.name}</option>)}</select>; }
function PackageSelect({ row, master, updateRow }: { row: ImportRow; master: ImportMasterData; updateRow: (id: number, patch: Partial<ImportRow>) => void }) { return <select className={inputClass} value={row.packageType} onChange={(event) => updateRow(row.rowNumber, { packageType: event.target.value })}>{master.packages.map((item) => <option key={item} value={item}>{translateStoredValue(item)}</option>)}</select>; }
function PayerSelect({ row, updateRow }: { row: ImportRow; updateRow: (id: number, patch: Partial<ImportRow>) => void }) { return <select className={inputClass} value={row.payerType} onChange={(event) => updateRow(row.rowNumber, { payerType: event.target.value as ImportRow["payerType"] })}><option value="client">לקוח</option><option value="venue">אולם</option></select>; }
function Errors({ row }: { row: ImportRow }) { return row.errors.length ? <ul className={`space-y-1 text-xs ${hasBlockingErrors(row) ? "text-destructive" : "text-amber-800"}`}>{row.errors.map((error) => <li key={error}>{error}</li>)}</ul> : <span className="text-xs text-emerald-700">תקין</span>; }
function Label({ text, children }: { text: string; children: React.ReactNode }) { return <label className="text-xs font-medium">{text}{children}</label>; }
function BulkControls({ bulk, master, onChange, onApply }: { bulk: BulkDefaults; master: ImportMasterData; onChange: (value: BulkDefaults) => void; onApply: <K extends keyof BulkDefaults>(key: K) => void }) { return <section className="rounded-xl border border-border bg-muted/20 p-4"><h3 className="mb-3 text-sm font-semibold">קביעה לכל האירועים</h3><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5"><Bulk label="קבע אולם לכל האירועים" onApply={() => onApply("venueId")}><select className={inputClass} value={bulk.venueId} onChange={(event) => onChange({ ...bulk, venueId: event.target.value })}><option value="">בחירת אולם</option>{master.venues.map((venue) => <option key={venue.id} value={venue.id}>{venue.name}</option>)}</select></Bulk><Bulk label="קבע שעת התחלה לכל האירועים" onApply={() => onApply("startTime")}><input type="time" className={inputClass} value={bulk.startTime} onChange={(event) => onChange({ ...bulk, startTime: event.target.value })} /></Bulk><Bulk label="קבע מחיר לאורח לכל האירועים" onApply={() => onApply("pricePerGuest")}><input type="number" min="0" step="0.01" className={inputClass} value={bulk.pricePerGuest} onChange={(event) => onChange({ ...bulk, pricePerGuest: event.target.valueAsNumber })} /></Bulk><Bulk label="קבע חבילת בר לכל האירועים" onApply={() => onApply("packageType")}><select className={inputClass} value={bulk.packageType} onChange={(event) => onChange({ ...bulk, packageType: event.target.value })}>{master.packages.map((item) => <option key={item} value={item}>{translateStoredValue(item)}</option>)}</select></Bulk><Bulk label="קבע מי משלם לכל האירועים" onApply={() => onApply("payerType")}><select className={inputClass} value={bulk.payerType} onChange={(event) => onChange({ ...bulk, payerType: event.target.value as BulkDefaults["payerType"] })}>{(["client", "venue"] as const).map((payer) => <option key={payer} value={payer}>{payerLabels[payer]}</option>)}</select></Bulk></div></section>; }
function Bulk({ label, children, onApply }: { label: string; children: React.ReactNode; onApply: () => void }) { return <div><p className="mb-1.5 text-xs font-medium">{label}</p>{children}<Button type="button" size="sm" variant="outline" className="mt-2 w-full" onClick={onApply}>החל על הכול</Button></div>; }
